### PR TITLE
Show most recent version update first + Fix typo

### PR DESCRIPTION
**Pull request by tomkerkhove**
- Show most recent version update first
- Fix typo
- Order parameters following the Azure convention

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Any update on this @daniellee?

**Comment by daniellee** [comment]
@tomkerkhove will merge it this week. Sorry for the delay.

**Comment by tomkerkhove** [comment]
@daniellee  No problem, I fixed the merge conflicts

**Comment by tomkerkhove** [comment]
Any update on this @daniellee?

**Comment by daniellee** [comment]
Thanks for the PR!

**Pull request merged**
