### PR TITLE
Feature: Add log analytics queries as an option, round 2!

### PR DESCRIPTION
**Pull request by judy**
I had an earlier pull request [here.](https://github.com/grafana/azure-monitor-datasource/pull/32) But merging it would have been a nightmare, since a major module was refactored and renamed shortly after my fork. I re-implemented my changes on top of the latest version of this datasource.

I hope this passes your standard. Please let me know at your latest convenience so I can stay on top of it, and hopefully won't have to merge against another big refactoring again. ;)

### CODE REVIEW

**Comment by dontjee** [comment]
I'm excited about this feature, thanks for putting in the effort @judy!

**Comment by daniellee** [comment]
I will be working on this plugin next week and will review all PR's then. Thanks for taking the time to update the original PR.

**Comment by daniellee** [comment]
Thank you so much for this! I am working on adding Monaco Editor integration with intellisense for KustoDB which can be used for this too so will hopefully add that in next week.

**Comment by daniellee** [comment]
Have a question: what's the Procfile for? 

I am also in the process of replacing grunt with webpack and karma with jest which I will be pushing to master today so don't want to mess anything up for your workfile.

**Comment by judy** [comment]
Woo! Excited to see webpack being used. I hadn't used grunt in a while and was rusty on it.

Re: Procfile, it's a language- and framework-agnostic way to define several processes that you want to run at once on the command line. Originated with [Foreman](http://blog.daviddollar.org/2011/05/06/introducing-foreman.html) back in 2011, and it's been ported to a [number of different languages](https://github.com/ddollar/foreman). Heroku adopted it as a simple format they could use so they'd know what processes to start. Deis started using it too.

Then the Evil Martians company [wrote their own version](https://evilmartians.com/chronicles/introducing-overmind-and-hivemind) from scratch, while keeping the same Procfile format. And they called it [Hivemind](https://github.com/DarthSim/hivemind). **Then** he wanted to make a more complex version that would let him manipulate processes individually, and called it [Overmind](https://github.com/DarthSim/overmind). But the Procfile still remains exactly the same.

I admit now, it's completely irrelevant to this pull request. Feel free to chuck it. But I find it incredibly useful and create one for every single project I have going on. The format is extremely simple to understand, just name your processes and put down what you'd write on the command line anyway.

**Pull request merged**
