### PR TITLE
Add Metric Namespace field/query

### PR DESCRIPTION
**Pull request by raphaelquati**
Implementation for #77

### CODE REVIEW

**Comment by dylan-asos** [comment]
Any help required to get this one in ?  Quite keen to have the ability to have our custom metrics in dashboards. 

Happy to take a build / test / whatever.

**Comment by SureshKhemka** [comment]
+1 need this to get telegraf metrics pushed to Azure monitor.

**Review by nhjiejan — APPROVED** [review]

**Comment by bmcstuff** [comment]
+1 also need this to view telegraf metrics pushed to Azure monitor

**Comment by nhjiejan** [comment]
Hi @raphaelquati , when i try to build the package i get:

```
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.
```

Any guidance on how to package this up?

Thanks

**Comment by raphaelquati** [comment]
> Hi @raphaelquati , when i try to build the package i get:
> 
> ```
> A valid Gruntfile could not be found. Please see the getting started guide for
> more information on how to configure grunt: http://gruntjs.com/getting-started
> Fatal error: Unable to find Gruntfile.
> ```
> 
> Any guidance on how to package this up?
> 
> Thanks

When I've write this, was chalenge to me to figure up how to package this.
I was using Grafana v5.3.4. I don't know if this plugin is compatible with newer version.
You need to put the plugin inside the grafana repo, at data/plugins (as pointed in https://grafana.com/docs/plugins/developing/development/) but there's no gruntfile.js as you noted.

You need to run "npm run-script build" to run webpack.

**Comment by daniellee** [comment]
@raphaelquati I would really like to port this PR over to the Grafana repo. This is totally my fault for not archiving this repo earlier. Do you want to do the port (so that you are the author and get cred for it) or do you want me to do it?

**Comment by raphaelquati** [comment]
PR created (https://github.com/grafana/grafana/pull/17282)

**Pull request closed without merging**
