### PR TITLE
Azure slots fix patch

### PR DESCRIPTION
**Pull request by nikos9742**
This PR is necessary to add correct support for Azure WebApp Slots. It changes the URL so the request are in line with the Azure API.

### CODE REVIEW

**Comment by sylr** [comment]
@DanCech @daniellee  Could you merge this please.

**Comment by daniellee** [comment]
@sylr on vacation this week and next but will review/merge this before the next release (the next release will be a large one that includes support for Log Analytics for Azure Monitor and for App Insights)

**Comment by sylr** [comment]
@daniellee could you merge this now ?

**Comment by sylr** [comment]
@daniellee could you please merge that

**Comment by daniellee** [comment]
Thanks for the PR but I found a more general solution to solve this problem: https://github.com/grafana/azure-monitor-datasource/commit/1698a5bdc7505f8c8ae7838de85864f0b216763f

The fix is released in v0.1.2.

**Pull request closed without merging**
