### PR TITLE
Feature: Add log analytics queries as an option

### PR DESCRIPTION
**Pull request by judy**
I've been writing a number of custom queries over on Application Insights, but only being able to search by individual metrics in this plugin was limiting. I thought I'd add the ability to write your own queries here too. It's *much* less user-friendly—but gives a lot more freedom to those who want to go the hard way.

Documentation of how the feature works was written out in the README.

### CODE REVIEW

**Comment by daniellee** [comment]
Thank you so much for the PR. Have been totally snowed under due to the Grafana 5.0 release but that is just about done. I will be working on this plugin during the next few weeks and this would be a great addition I think.

**Comment by mbernard** [comment]
Nice work! I'm really looking forward for this feature. Do you have an ETA of when it will be merged back and available in the hosted version of Grafana?

**Comment by daniellee** [comment]
I just did a release of the app so will be merging this soon.

**Comment by judy** [comment]
Looks like merging this turned out to be a nightmare. There was a refactoring shortly after I branched and variables were added. I'm making a new branch off of master and will send a new pull request.

**Pull request closed without merging**
