### PR TITLE
WIP: Log analytics. Fixes #56

### LINKED ISSUE #56: Add support for Azure Monitor Log Analytics
- [x] Integrate the Monaco editor
- [x] Integrate the KustoDB Language Service to get intellisense
- [x] Add a new option for Log Analytics and integrate the [Log Analytics API](https://portal.loganalytics.io/demo)
- [x] Support parsing the data into time series format
- [x] Support parsing the data into table format
- [x] Documentation
- [x] Support switching Workspace in the query editor
- [x] Have Run button like the analytics portal has
- [x] Show the raw query after executing
- [x] Slim down the Monaco editor js file by removing unneeded features (currently 8MB uncompressed)
- [x] Use the /metadata endpoint to get the schema (/query/schema will be deprecated) and for multiple databases/solutions put into one virtual database for the intellisense schema.
- [x] Investigate which AAD role is needed and document it.
- [x] Improve Intellisense for Grafana macros - getting double entries in the list sometimes.
- [x] Template variable support
- [x] Annotation support
- [x] Handle Esc button when in monaco editor.
- [ ] Support for Azure Gov
- [x] Monaco Code Editor refactoring
- [ ] Add throttling support when autorefreshing (use the API to find out when requests are throttled and wait for the retry-after period)
- [x] Add message that it requires Grafana 5.3.

### PR DESCRIPTION
**Pull request by daniellee**
See #56 for details. WIP

### CODE REVIEW

**Comment by asaflevi1983** [comment]
I installed this branch on my Grafana.
I connected the plugin to my azure monitor and aplication insight  services.
it looks like I cant connect to my workspaces, I am always getting DEMO_WORKSPACE.

**the following code is suspicious:**

 AzureLogAnalyticsDatasource.prototype.getWorkspaces = function () {
        var workspaceListUrl = this.azureMonitorUrl + '/providers/Microsoft.OperationalInsights/workspaces?api-version=2017-04-26-preview';
        return this.doRequest(workspaceListUrl).then(function (response) {
            // return _.map(response.data.value, 'name') || [];
            return ['DEMO_WORKSPACE'];
        });
    };

**Comment by asaflevi1983** [comment]
I tried to build the plugin using the command: 
**yarn run**
and then choosing to **build**.
I am getting the following error: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

do you know how to increase the nodejs memory using yarn?

**Comment by daniellee** [comment]
@asaflevi1983 this really is a WIP (work in progress) and is not ready for testing yet. For example, this commit is hardcoded to use the demo account. Thanks for trying it out but it should be testable/usable today or tomorrow.

**Comment by ramonTC** [comment]
@daniellee Hi Danielle, when is that issue expected to be solved ?
Thx!

**Comment by ramonTC** [comment]
@daniellee I meant Log Analytics support for Azure monitor.
Thx for the info.

**Pull request merged**
